
#Choose a base image
FROM node:6.10.3-alpine

# Create a new folder for our application
RUN mkdir -p /usr/src/app

# Set the working dir when our container executes
WORKDIR /usr/src/app

# Copy our package.json file
ADD package.json /usr/src/app

RUN apk add --no-cache make gcc g++ python

# Install our packages
RUN npm install

# Copy the rest of our application
COPY ./utils /usr/src/app

#Expose our application port
EXPOSE 3000

# Set start command
CMD ["node", "provision.js", "config.json", "cbdb1", "cbdb2", "cbdb3", "cbdb4", "cbdb5" ]
