version: '3'

services:
    cbdb1:
        image: couchbase/server:4.6.1
        ports:
            - "8091-8094:8091-8094"
            - "11207-11210:11207-11210"
            - "18091-18094:18091-18094"
    cbdb2:
        image: couchbase/server:4.6.1
        ports:
            - "9091-9094:8091-8094"
    cbdb3:
        image: couchbase/server:4.6.1
        ports:
            - "10091-10094:8091-8094"
    cbdb4:
        image: couchbase/server:4.6.1
        ports:
            - "11091-11094:8091-8094"
    cbdb5:
        image: couchbase/server:4.6.1
        ports:
            - "12091-12094:8091-8094"
    nodejs:
        build:
          context: .
          dockerfile: Dockerfile-Node-App
